# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
# xcodebuild build-for-testing -workspace MyWorkspace.xcworkspace -scheme MyScheme -destination generic/platform=iOS
# xcodebuild build-for-testing -workspace SwiftyKit.xcworkspace -target SwiftyKit_Tests -destination generic/platform=iOS
# xcodebuild build-for-testing -workspace SwiftyKit.xcworkspace -scheme SwiftyKit_Tests -destination generic/platform=iOS
# xcodebuild build-for-testing -workspace SwiftyKit.xcworkspace -scheme SwiftyKit-Example -destination generic/platform=iOS
# xcodebuild test -workspace SwiftyKit.xcworkspace -scheme SwiftyKit-Example -destination 'platform=iOS Simulator,name=iPhone 7' | xcpretty
# xcodebuild test -workspace SwiftyKit.xcworkspace -scheme SwiftyKit_Tests -destination 'platform=iOS Simulator,name=iPhone 7' | xcpretty

# - set -o pipefail && xcodebuild test -workspace SwiftyKit.xcworkspace -scheme SwiftyKit-Example -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.0' | xcpretty
# - set -o pipefail && xcodebuild test -workspace SwiftyKit.xcworkspace -scheme SwiftyKit_Tests -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.0' | xcpretty
# - set -o pipefail && xcodebuild test -workspace SwiftyKit.xcworkspace -scheme SwiftyKit-Example -destination 'platform=iOS Simulator,name=iPhone SE,OS=11.0' | xcpretty
# - set -o pipefail && xcodebuild test -workspace SwiftyKit.xcworkspace -scheme SwiftyKit_Tests -destination 'platform=iOS Simulator,name=iPhone SE,OS=11.0' | xcpretty
script:
- set -o pipefail && xcodebuild test -workspace SwiftyKit.xcworkspace -scheme SwiftyKit-Example -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.0' | xcpretty
- set -o pipefail && xcodebuild test -workspace SwiftyKit.xcworkspace -scheme SwiftyKit_Tests -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.0' | xcpretty
- set -o pipefail && xcodebuild test -workspace SwiftyKit.xcworkspace -scheme SwiftyKit-Example -destination 'platform=iOS Simulator,name=iPhone SE,OS=11.0' | xcpretty
- set -o pipefail && xcodebuild test -workspace SwiftyKit.xcworkspace -scheme SwiftyKit_Tests -destination 'platform=iOS Simulator,name=iPhone SE,OS=11.0' | xcpretty
- pod lib lint
