# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.2
language: objective-c

cache:
  - bundler
  - cocoapods

env:
    global:
        - LC_CTYPE=en_US.UTF-8
        - LANG=en_US.UTF-8

matrix:
  include:
    - env: RUN_SCHEME="SwiftyKit-Example"
    - env: RUN_SCHEME="SwiftyKit_Tests"
    - env: RUN_SCHEME="SwiftyKit_Networking_Tests"
    - env: RUN_SCHEME="SwiftyKit_CoreData_Tests"

script:
  - echo $RUN_SCHEME
  - echo $RUN_DESTINATION
  - set -o pipefail
  - xcodebuild test -workspace SwiftyKit.xcworkspace -scheme $RUN_SCHEME -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0.1' -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.1' | xcpretty
  - pod lib lint
